


rule all:
    input: 
        "measles.fa.fai",
        "measles.fa.gz"



rule download_fasta:
    input:
    output: "measles.fa"
    shell:
        """
        bioservices download-accession --accession K01711.1 --output {output}
        """


rule faidx:
    input: "measles.fa"
    output: "measles.fa.fai"
    shell:
        """
        samtools faidx measles.fa
        """

rule gzip:
    input: "measles.fa"
    output: "measles.fa.gz"
    shell:
        """
        gzip -c {input} > {output}
        """
